MOD_UMINIZ_DIR := $(USERMOD_DIR)

CFLAGS_USERMOD += -DMICROPY_PY_UMINIZ
CFLAGS_USERMOD += -DMINIZ_NO_STDIO
CFLAGS_USERMOD += -DMINIZ_NO_TIME
CFLAGS_USERMOD += -DMINIZ_NO_ARCHIVE_APIS
CFLAGS_USERMOD += -DMINIZ_NO_ARCHIVE_WRITING_APIS

CFLAGS_USERMOD += -I$(MOD_UMINIZ_DIR)
CFLAGS_USERMOD += -I$(MOD_UMINIZ_DIR)/miniz/

SRC_USERMOD += $(MOD_UMINIZ_DIR)/miniz/miniz.c
SRC_USERMOD += $(MOD_UMINIZ_DIR)/miniz/miniz_tinfl.c
SRC_USERMOD += $(MOD_UMINIZ_DIR)/miniz/miniz_tdef.c
SRC_USERMOD += $(MOD_UMINIZ_DIR)/miniz/miniz_zip.c
SRC_USERMOD += $(MOD_UMINIZ_DIR)/moduminiz.c
